// Offline court workspaces and central scoring share the same match-level merge rules.
let syncSession=null,syncBusy=false,syncIssue=null,selectedCourts={},syncNote='尚未啟用連線同步';
const coordKey=KEY+'-sync';
try{syncSession=JSON.parse(localStorage.getItem(coordKey)||'null');}catch(e){}
if(courtConfig&&syncSession&&Engine.eventKey(syncSession.base)!==Engine.eventKey(courtConfig.base))syncSession=null;
if(courtConfig&&!syncSession)syncSession={base:courtConfig.base,url:courtConfig.connection?.url||'',token:courtConfig.connection?.token||'',worker:true};
function packetFor(base,current,court=courtConfig?.court||'*'){return {type:'school-court-records',version:1,court,base,state:current,exportedAt:new Date().toISOString()};}
function pendingCount(){const base=syncSession?.base||courtConfig?.base;if(!base||Engine.eventKey(base)!==Engine.eventKey(state))return 0;return Engine.build(state).matches.filter(m=>(!courtConfig||base.assignments[m.id]?.court===courtConfig.court)&&Engine.canonical(Engine.matchRecord(base,m.id,!courtConfig))!==Engine.canonical(Engine.matchRecord(state,m.id,!courtConfig))).length;}
function courtAllowed(id){return !courtConfig||state.assignments[id]?.court===courtConfig.court;}
function courtsHTML(graph,values){const courts=courtConfig?[courtConfig.court]:Engine.courtIds(state.settings.courts);let h='<div class="sectionlabel"><h3>場地集中計分</h3><span class="small">同一份賽事資料 · 每次計分立即保存</span></div><div class="court-grid">';for(const court of courts){const list=graph.matches.filter(m=>(state.assignments[m.id]?.court||defaultCourt(m))===court&&!['bye','unneeded','conditional'].includes(values[m.id].status));const active=list.find(m=>state.matchTimes?.[m.id]&&!state.results[m.id]);const ready=list.filter(m=>values[m.id].status==='ready').sort((a,b)=>(state.assignments[a.id]?.time||'').localeCompare(state.assignments[b.id]?.time||'')||a.number-b.number);const m=active||ready.find(m=>m.id===selectedCourts[court])||ready[0];h+=`<section class="court-tile"><h3>場地 ${court}${active?' · 進行中':''}</h3>`;if(!m){h+='<p class="hint">目前沒有可開打場次，等待前場結果。</p></section>';continue;}const v=values[m.id],entry=state.entries?.[m.id]||{},sets=state.settings.score==='sets';h+=`<label class="field"><span>場次</span><select class="court-match-select" data-court="${court}" aria-label="場地 ${court} 選擇場次" ${active?'disabled':''}>${(active?[active]:ready).map(x=>`<option value="${x.id}" ${x.id===m.id?'selected':''}>${x.id} · ${esc(name(values[x.id].a))} 對 ${esc(name(values[x.id].b))}</option>`).join('')}</select></label><div class="court-sides">`;for(const [side,p,key]of [['a',v.a,sets?'currentA':'sa'],['b',v.b,sets?'currentB':'sb']]){const score=Number(entry[key]||0),best=state.settings.score==='best3'?Engine.best3(entry.sets||''):null;h+=`<div><b>${esc(name(p))}</b><div class="court-counter"><button data-quick="${m.id}" data-side="${side}" data-delta="-1" aria-label="場地 ${court} ${side==='a'?'第一方':'第二方'}減一分" ${active&&state.locked&&score>0&&!displayMode&&(!best||best.sets.endsWith(side==='a'?'1:0':'0:1'))?'':'disabled'}>−</button><strong>${score}</strong><button data-quick="${m.id}" data-side="${side}" data-delta="1" aria-label="場地 ${court} ${side==='a'?'第一方':'第二方'}加一分" ${active&&state.locked&&score<999&&!displayMode&&!best?.complete?'':'disabled'}>＋</button></div></div>`;}h+='</div>';if(state.settings.score==='best3')h+='<p class="hint">三戰兩勝 · ＋ 記錄贏一局，− 撤回上一局</p>';if(sets)h+=`<p class="hint">本局分數 · 已記錄各局：${esc(entry.sets||'尚無')}</p>`;h+=`<div class="row manage">${!active?`<button class="quick-start primary" data-id="${m.id}" ${state.locked?'':'disabled'}>開始 ${m.id}</button>`:''}<button class="quick-detail" data-id="${m.id}">${active?'記錄本局／結束比賽':'開啟場次記分板'}</button></div></section>`;}return h+'</div>';}
function quickPoint(id,side,delta){if(state.settings.score==='best3'){if(displayMode||!state.locked||!courtAllowed(id)||!state.matchTimes?.[id]||state.results[id])return;try{const old=state.entries?.[id]||{},score=Engine.best3Change(old,side,delta);state.entries??={};state.entries[id]={sa:String(score.sa),sb:String(score.sb),sets:score.sets,type:old.type||'normal',winner:old.winner||''};save();render();}catch(e){notify(e.message);}return;}if(displayMode||!state.locked||!courtAllowed(id)||!state.matchTimes?.[id]||state.results[id])return;const v=Engine.resolve(state)[id];if(v?.status!=='ready')return;const previous=state.entries?.[id]||{},key=state.settings.score==='sets'?(side==='a'?'currentA':'currentB'):(side==='a'?'sa':'sb');const value=Number(previous[key]||0);if(!Number.isInteger(value)||value<0||value>999)return notify('請先在場次視窗確認比分');state.entries??={};state.entries[id]={sa:'0',sb:'0',sets:'',type:'normal',winner:'',...previous,[key]:String(Math.max(0,Math.min(999,value+delta)))};save();render();}
function renderCoord(){if(displayMode)return;const box=$('coordinationPanel');if(!box)return;box.innerHTML=courtConfig?`<b>場地 ${courtConfig.court} 離線計分</b><span>${pendingCount()} 場尚未整合 · ${esc(syncNote)}</span><button id="exportCourtRecords">匯出場地紀錄</button><button id="manualSync">立即同步</button>`:`<b>場地資料整合</b><span>${esc(syncNote)}${syncSession?' · 待同步 '+pendingCount()+' 場':''}</span><button id="enableHub">主電腦啟用連線同步</button><button id="importCourtRecords">匯入場地紀錄</button><button id="manualSync">立即同步</button><div class="row">${Engine.courtIds(state.settings.courts).map(c=>`<button class="export-court" data-court="${c}">下載場地 ${c} 計分網頁</button>`).join('')}</div>${syncSession?.url?'<span class="small">場地裝置連線地址：'+esc(syncSession.lanUrl||syncSession.url)+'/court（選擇場地並輸入連線碼） · 連線碼：'+esc(syncSession.workerToken||syncSession.token)+'</span>':''}`;if(syncIssue)box.innerHTML+='<button id="resolveSync" class="danger">查看同步衝突</button>';$('exportCourtRecords')?.addEventListener('click',()=>{download(JSON.stringify(packetFor(syncSession?.base||courtConfig.base,state,courtConfig.court),null,2),'application/json;charset=utf-8',filename('場地'+courtConfig.court+'.json'));notify('已送出場地紀錄下載；匯入主電腦後才完成整合');});$('importCourtRecords')?.addEventListener('click',()=>$('courtRecordFile').click());$('enableHub')?.addEventListener('click',enableHub);$('manualSync')?.addEventListener('click',()=>syncTick(true));$('resolveSync')?.addEventListener('click',()=>showConflicts(syncIssue));for(const b of box.querySelectorAll('.export-court'))b.onclick=()=>exportCourtHTML(b.dataset.court);}
function exportCourtHTML(court){if(!state.locked||!state.draw)return notify('請先完成抽籤並確認賽程');const copy=document.documentElement.cloneNode(true),config={court,base:structuredClone(state),connection:syncSession?.url?{url:syncSession.lanUrl||syncSession.url,token:syncSession.workerToken||syncSession.token}:null};copy.querySelector('#court-config').textContent=JSON.stringify(config).replace(/</g,()=>String.fromCharCode(92)+'u003c');copy.querySelector('#portable-data').textContent=JSON.stringify(state).replace(/</g,()=>String.fromCharCode(92)+'u003c');for(const d of copy.querySelectorAll('dialog'))d.removeAttribute('open');for(const id of ['content','matchContent','setupDrawContent','coordinationPanel'])copy.querySelector('#'+id).innerHTML='';copy.querySelector('#matchDialog').classList.remove('scoreboard','show-score-details');copy.querySelector('body').classList.remove('screen','court-worker','page-focus','native-fullscreen');copy.querySelector('#toast').classList.add('hidden');download('<!doctype html>'+copy.outerHTML,'text/html;charset=utf-8',filename('場地'+court+'.html'));notify('已送出場地 '+court+' 計分網頁下載；請先在計分裝置開啟並確認名單');}
function shortRecord(r){if(r.settings)return r.settings.title+'／'+r.settings.courts+' 個場地';return r.result?`比分 ${r.result.sa}:${r.result.sb}，${name(r.result.winner)} 勝`:r.entry?`計分 ${r.entry.currentA??r.entry.sa}:${r.entry.currentB??r.entry.sb}`:r.time?'已開始比賽':'尚無比分';}
function showConflicts(job){job.packet.expected=Object.fromEntries(job.conflicts.map(c=>[c.id,c.local]));if(job.online){job.packet.state=structuredClone(state);job.packet.expected={};for(const c of job.conflicts){c.incoming=Engine.matchRecord(state,c.id,!courtConfig);job.packet.expected[c.id]=c.local;}}const dialog=$('mergeDialog');$('mergeContent').innerHTML='<p>同一場有不同紀錄，請逐場選擇。更正勝負可能影響晉級；系統會先備份。</p>'+job.conflicts.map(c=>`<label class="field"><b>${esc(c.id)} · ${esc(c.reason)}</b><span>${job.online?'主電腦':'目前'}：${esc(shortRecord(c.local))} ／ ${job.online?'此裝置':'匯入'}：${esc(shortRecord(c.incoming))}</span><select data-conflict="${esc(c.id)}"><option value="">請選擇</option><option value="local">保留${job.online?'主電腦':'目前'}紀錄</option><option value="incoming">採用${job.online?'此裝置':'匯入'}紀錄</option></select></label>`).join('');$('mergeApply').onclick=async()=>{const choices={};for(const el of dialog.querySelectorAll('[data-conflict]')){if(!el.value)return notify('請逐場選擇要保留的紀錄');choices[el.dataset.conflict]=el.value;}try{if(job.online){const data=await syncRequest('/api/sync',{packet:job.packet,choices});if(data.conflicts?.length)throw Error('主電腦紀錄已變動，請重新同步確認');acceptSync(data,job.packet.state);syncIssue=null;}else{const merged=Engine.mergeRecords(state,job.packet,choices);if(merged.conflicts.length)throw Error('場地已重新分配，無法覆蓋，請重新取得場地網頁');backup();state=merged.state;log('人工確認場地紀錄衝突：'+Object.keys(choices).join('、'));save();render();}dialog.close();notify('紀錄已整合');}catch(e){notify(e.message);}};if(!dialog.open)dialog.showModal();}
async function importCourtFile(file){if(!file)return;try{if(file.size>10*1024*1024)throw Error('紀錄檔過大');const packet=JSON.parse(await file.text());if(packet.court==='*')throw Error('請選擇各場地匯出的紀錄檔');const merged=Engine.mergeRecords(state,packet);if(merged.conflicts.length)return showConflicts({packet,conflicts:merged.conflicts,online:false});if(merged.changes.length){backup();state=merged.state;log('匯入場地 '+packet.court+'：'+merged.changes.join('、'));save();render();}notify('整合 '+merged.changes.length+' 場，略過 '+merged.duplicates+' 場重複紀錄');}catch(e){notify('無法整合：'+e.message);}}
async function syncRequest(path,body){const response=await fetch(syncSession.url+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json','X-Sync-Token':syncSession.token},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(6000)});const data=await response.json();if(!response.ok&&!data.conflicts)throw Error(data.error||'同步失敗');return data;}
async function enableHub(){if(syncSession?.url&&Engine.eventKey(syncSession.base)===Engine.eventKey(state)){await syncTick(true);return notify('目前賽事已啟用同步');}try{const response=await fetch('/api/info',{signal:AbortSignal.timeout(4000)}),info=await response.json();if(!response.ok)throw Error(info.error||'請使用連線版啟動程式');if(!state.locked||!state.draw)throw Error('請先完成抽籤並確認賽程');const previous=syncSession;syncSession={url:location.origin,token:info.masterToken,workerToken:info.workerToken,lanUrl:info.lanUrl,base:structuredClone(state),worker:false};try{await syncRequest('/api/register',{state});}catch(e){syncSession=previous;throw e;}localStorage.setItem(coordKey,JSON.stringify(syncSession));syncNote='連線同步已啟用';renderCoord();}catch(e){notify('無法啟用：'+e.message+'。離線計分及檔案整合仍可使用。');}}
function acceptSync(data,sent){const remote=Engine.validate(data.state),local=Engine.mergeRecords(state,packetFor(sent,remote,'*'));if(local.conflicts.length)throw Error('同步期間此場又被修改，請重新同步確認');state=local.state;syncSession.base=remote;localStorage.setItem(coordKey,JSON.stringify(syncSession));primarySave();syncNote='已同步 '+new Date().toLocaleTimeString('zh-TW');if($('matchDialog').open||['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))renderCoord();else render();}
async function syncTick(manual=false){if(!syncSession?.url){if(manual)notify('尚未啟用連線同步；可匯出場地紀錄交給主電腦，或重新取得含連線設定的場地網頁');return;}if(syncBusy||syncIssue||displayMode)return;if(Engine.eventKey(syncSession.base)!==Engine.eventKey(state)){syncNote='賽事已變更，請主電腦重新啟用同步';renderCoord();return;}syncBusy=true;const sent=structuredClone(state),packet=packetFor(syncSession.base,sent);try{const data=await syncRequest('/api/sync',{packet});if(data.conflicts?.length){syncIssue={packet,conflicts:data.conflicts,online:true};syncNote='有不同紀錄，等待確認';renderCoord();if(manual)showConflicts(syncIssue);}else acceptSync(data,sent);}catch(e){syncNote='未連線／尚未整合，本機紀錄已保留';renderCoord();if(manual)notify(e.message+'；可改用匯出場地紀錄。');}finally{syncBusy=false;}}
const primarySave=save,primaryRender=render,primaryBind=bindContent,primaryOpenMatch=openMatch,primaryStartMatch=startMatch;
save=function(){primarySave();renderCoord();};
render=function(){if(courtConfig)tab='courts';primaryRender();if(courtConfig)for(const el of document.querySelectorAll('#matchRoot .court,#matchRoot .time'))el.disabled=true;renderCoord();};
bindContent=function(){primaryBind();for(const el of document.querySelectorAll('[data-quick]'))el.onclick=()=>quickPoint(el.dataset.quick,el.dataset.side,Number(el.dataset.delta));for(const el of document.querySelectorAll('.quick-start'))el.onclick=()=>startMatch(el.dataset.id);for(const el of document.querySelectorAll('.quick-detail'))el.onclick=()=>openMatch(el.dataset.id);for(const el of document.querySelectorAll('.court-match-select'))el.onchange=()=>{selectedCourts[el.dataset.court]=el.value;render();};};
openMatch=function(id){if(!courtAllowed(id))return notify('此網頁只記錄場地 '+courtConfig.court);primaryOpenMatch(id);if(courtConfig)for(const el of document.querySelectorAll('#matchRoot .court,#matchRoot .time'))el.disabled=true;};
startMatch=function(id){if(courtAllowed(id))primaryStartMatch(id);};
// The worker deliberately exposes only its assigned matches; result correction uses the normal confirmation flow.
const panel=$('coordinationPanel')||document.createElement('section');panel.id='coordinationPanel';panel.className='card coordination';$('content').parentElement.before(panel);
if(!document.querySelector('[data-tab=courts]')){const button=document.createElement('button');button.className='tab';button.dataset.tab='courts';button.textContent='場地計分';button.onclick=()=>{tab='courts';render();};document.querySelector('.tabs').append(button);}
const fileInput=$('courtRecordFile')||document.createElement('input');fileInput.id='courtRecordFile';fileInput.type='file';fileInput.accept='.json,application/json';fileInput.hidden=true;fileInput.onchange=()=>{importCourtFile(fileInput.files[0]);fileInput.value='';};document.body.append(fileInput);
const mergeDialog=$('mergeDialog')||document.createElement('dialog');mergeDialog.id='mergeDialog';mergeDialog.innerHTML='<h2>比賽紀錄衝突</h2><div id="mergeContent"></div><div class="row"><button id="mergeCancel">稍後處理</button><button id="mergeApply" class="primary">確認整合</button></div>';document.body.append(mergeDialog);$('mergeCancel').onclick=()=>mergeDialog.close();
if(courtConfig){document.body.classList.add('court-worker');$('setupDialog').close();for(const id of ['settingsBtn','backupBtn','loadBtn','portableBtn','displayBtn'])$(id).hidden=true;document.querySelector('.tabs').hidden=true;tab='courts';}
render();setInterval(()=>syncTick(),3000);
