const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const html=fs.readFileSync('index.html','utf8');
new vm.Script(html.match(/<script id="app">([\s\S]*?)<\/script>/)[1]);
new vm.Script(html.match(/<script id="coordination">([\s\S]*?)<\/script>/)[1]);
assert.equal(html.match(/<script id="coordination">([\s\S]*?)<\/script>/)[1].trim(),fs.readFileSync('coordination.js','utf8').trim(),'離線網頁需包含最新版整合功能');
const sandbox={crypto:require('crypto').webcrypto,structuredClone};
vm.createContext(sandbox);vm.runInContext(html.match(/<script id="engine">([\s\S]*?)<\/script>/)[1]+'\nthis.E=Engine;',sandbox);
const E=sandbox.E;let checks=0;
function state(n,mode,bronze=false){const people=Array.from({length:n},(_,i)=>({id:'P'+i,name:'隊伍'+i,className:'',seat:''}));return {version:1,id:'test',settings:{mode,kind:'class',title:'測試',sport:'排球',courts:2,score:'total',bronze},people,draw:E.reveal(E.createDraw(people,mode),n),results:{},assignments:{},audit:[],locked:true};}
function run(n,mode,bronze,reset){let s=state(n,mode,bronze),g=E.build(s),losses={},played=0;while(true){const vs=E.resolve(s,g),ready=g.matches.filter(m=>vs[m.id].status==='ready');if(!ready.length)break;for(const m of ready){const v=vs[m.id];let winner=m.grandFinal?(reset?v.b:v.a):(played%3?v.a:v.b);if(m.resetOf)winner=v.b;assert.notEqual(v.a,v.b,'不可自己對自己');assert.ok((losses[v.a]||0)<(mode==='double'?2:1)||m.bronze);assert.ok((losses[v.b]||0)<(mode==='double'?2:1)||m.bronze);const loser=winner===v.a?v.b:v.a;losses[loser]=(losses[loser]||0)+1;s.results[m.id]={a:v.a,b:v.b,winner,sa:winner===v.a?21:15,sb:winner===v.b?21:15,sets:'',type:'normal'};played++;}if(played>300)throw Error('無法終止');}
 const vs=E.resolve(s,g),champ=E.champion(s,g,vs);assert.ok(champ,'必須產生冠軍');const expected=mode==='double'?2*n-2+(reset?1:0):n-1+(bronze?1:0);assert.equal(played,expected,`${n} ${mode} 場數`);if(mode==='double'){for(const p of s.people)assert.equal(losses[p.id]||0,p.id===champ?(reset?1:0):2,'雙敗淘汰敗數');}assert.equal(g.matches.filter(m=>['ready','waiting'].includes(vs[m.id].status)).length,0,'不能卡住');E.validate(JSON.parse(JSON.stringify(s)));
 const resultsBefore=Object.keys(s.results).length,first=Object.keys(s.results)[0],affected=E.descendants(g,first);for(const id of affected)delete s.results[id];E.validate(JSON.parse(JSON.stringify(s)));assert.ok(Object.keys(s.results).length<resultsBefore);checks++;return s;}
for(const n of [2,3,4,5,6,7,8,9,15,16,17,18,30,31,32,33,63,64,65,127,128]){run(n,'single',false,false);if(n>=4)run(n,'single',true,false);run(n,'double',false,false);run(n,'double',false,true);if(n>=4){run(n,'groups',false,false);run(n,'groups',true,false);}}
for(let i=0;i<100;i++){const s=state(18,'single');assert.equal(new Set(s.draw.pool).size,18);assert.equal(s.draw.groups[0].slots.filter(x=>x===null).length,14);for(let k=0;k<32;k+=2)assert.ok(s.draw.groups[0].slots[k]||s.draw.groups[0].slots[k+1]);}
const partial=state(30,'single');partial.draw=E.createDraw(partial.people,'single');for(let i=0;i<30;i++){partial.draw=E.reveal(partial.draw,1);assert.equal(partial.draw.revealed,i+1);E.validate(JSON.parse(JSON.stringify(partial)));}
assert.equal(E.roster('班級\t座號\t姓名\n801\t1\t王小明\n801\t2\t王小明','person').length,2);assert.throws(()=>E.roster('801\n801','class'));assert.throws(()=>E.roster('801\t1\t甲\n801\t1\t乙','person'));assert.equal(E.csv('"801","王,小明"\r\n802,乙')[0][1],'王,小明');assert.throws(()=>E.validate({version:1}));
const timed=state(4,'single');timed.settings.date='2026-10-05';timed.settings.startTime='09:30';timed.settings.duration=20;const tv=E.resolve(timed)['M1'];timed.matchTimes={M1:{a:tv.a,b:tv.b,startedAt:'2026-10-04T09:00:00.000Z',endedAt:null}};let restored=E.validate(JSON.parse(JSON.stringify(timed)));assert.equal(restored.matchTimes.M1.startedAt,timed.matchTimes.M1.startedAt);assert.equal(restored.settings.startTime,'09:30');timed.results.M1={a:tv.a,b:tv.b,winner:tv.a,sa:21,sb:15,sets:'',type:'normal'};timed.matchTimes.M1.endedAt='2026-10-04T09:20:00.000Z';assert.equal(E.validate(timed).matchTimes.M1.endedAt,timed.matchTimes.M1.endedAt);const stale=structuredClone(timed);stale.matchTimes.M1.a='wrong';assert.throws(()=>E.validate(stale));const backwards=structuredClone(timed);backwards.matchTimes.M1.endedAt='2026-10-04T08:00:00.000Z';assert.throws(()=>E.validate(backwards));const invalidSettings=structuredClone(timed);invalidSettings.settings.startTime='25:99';assert.throws(()=>E.validate(invalidSettings));
const bad=state(18,'single');bad.draw.groups[0].slots[1]=bad.draw.groups[0].slots[0];assert.throws(()=>E.validate(bad));
const live=state(18,'single');live.settings.score='sets';live.entries={M1:{sa:'0',sb:'0',sets:'21:18',currentA:'5',currentB:'7',type:'normal',winner:''}};const resumed=E.validate(JSON.parse(JSON.stringify(live)));assert.equal(resumed.entries.M1.currentA,'5');assert.equal(resumed.entries.M1.currentB,'7');assert.equal(resumed.entries.M1.sets,'21:18');const negative=structuredClone(live);negative.entries.M1.currentA='-1';assert.throws(()=>E.validate(negative));
let schedules=0;
for(const n of [3,4,5,18,30,128])for(const mode of ['single','double','groups']){if(mode==='groups'&&n<4)continue;for(const courts of [1,2,3,4]){const sample=state(n,mode,mode!=='double'&&n>=4);Object.assign(sample.settings,{date:'2026-10-05',startTime:'09:00',duration:30,courts});const plan=E.schedule(sample),g=E.build(sample),vs=E.resolve(sample,g),duration=30*60000;for(const m of g.matches){if(vs[m.id].status==='bye')continue;const p=plan[m.id];assert.ok(p,'每場必須排定');for(const r of [m.a,m.b])if(r.match&&plan[r.match])assert.ok(p.start>=plan[r.match].end,'前場未結束不可上場');if(m.resetOf)assert.ok(p.start>=plan[m.resetOf].end,'決勝加賽必須等待前場結束');}for(const court of ['A','B','C','D']){const list=Object.values(plan).filter(p=>p&&!p.bye&&p.court===court).sort((a,b)=>a.start-b.start);for(let i=1;i<list.length;i++)assert.ok(list[i].start>=list[i-1].end,'同場地不可重疊');}schedules++;}}
const delayed=state(4,'single');delayed.matchTimes={};Object.assign(delayed.settings,{date:'2026-10-05',startTime:'09:00',duration:30,courts:2});const dv=E.resolve(delayed);for(const id of ['M1','M2']){const v=dv[id];delayed.results[id]={a:v.a,b:v.b,winner:v.a,sa:21,sb:15,sets:'',type:'normal'};delayed.assignments[id]={court:id==='M1'?'A':'B',time:'2026-10-05T09:00'};delayed.matchTimes[id]={a:v.a,b:v.b,startedAt:'2026-10-05T01:00:00Z',endedAt:id==='M1'?'2026-10-05T01:45:00Z':'2026-10-05T01:30:00Z'};}
const moment=Date.parse('2026-10-05T01:46:00Z'),dp=E.schedule(delayed,moment);assert.equal(dp.M1.start,Date.parse(delayed.matchTimes.M1.startedAt));assert.ok(dp.M3.start>=moment);assert.ok(dp.M3.start<Date.parse('2026-10-05T02:15:00Z'),'參考休息不應硬性延後');const notice=E.fairnessNotice(delayed,'M3',moment);assert.equal(notice.recent.length,2);assert.equal(notice.alternatives.length,0);assert.equal(E.fairnessNotice(delayed,'M3',Date.parse('2026-10-05T02:16:00Z')),null);
// Four first-round games can be interleaved before semifinal participants play again.
for(const courts of [1,2]){const sample=state(8,'single');Object.assign(sample.settings,{date:'2026-10-05',startTime:'09:00',duration:30,courts});const plan=E.schedule(sample);for(const id of ['M5','M6'])assert.ok(plan[id].start>=Math.max(...['M1','M2','M3','M4'].map(x=>plan[x].end)),'先穿插其他隊伍首輪再打準決賽');}
const available=state(8,'single');available.matchTimes={};Object.assign(available.settings,{date:'2026-10-05',startTime:'09:00',duration:30});const av=E.resolve(available);for(const id of ['M1','M2']){const v=av[id];available.results[id]={a:v.a,b:v.b,winner:v.a,sa:21,sb:15,sets:'',type:'normal'};available.matchTimes[id]={a:v.a,b:v.b,startedAt:'2026-10-05T01:00:00Z',endedAt:'2026-10-05T01:30:00Z'};}const hint=E.fairnessNotice(available,'M5',Date.parse('2026-10-05T01:31:00Z'));assert.deepEqual(Array.from(hint.alternatives),['M3','M4']);

for(const courts of [3,4]){const sample=state(18,'single');Object.assign(sample.settings,{date:'2026-10-05',startTime:'09:00',duration:30,courts});const plans=E.schedule(sample);for(const [id,p]of Object.entries(plans))if(p&&!p.bye)sample.assignments[id]={court:p.court,time:new Date(p.start).toISOString()};const restored=E.validate(JSON.parse(JSON.stringify(sample)));assert.equal(restored.settings.courts,courts);assert.ok(Object.values(restored.assignments).some(a=>a.court===E.courtIds(courts).at(-1)),'應使用所有場地');const invalid=structuredClone(sample);invalid.settings.courts=5;assert.throws(()=>E.validate(invalid));}
const central=state(8,'single');Object.assign(central.settings,{courts:4,date:'2026-10-05',startTime:'09:00',duration:30});central.entries={};central.matchTimes={};for(let i=1;i<=4;i++)central.assignments['M'+i]={court:'ABCD'[i-1],time:'2026-10-05T09:00'};let integrated=structuredClone(central);let packets=[];for(let i=1;i<=4;i++){const worker=structuredClone(central),id='M'+i,v=E.resolve(worker)[id];worker.entries[id]={sa:String(i),sb:'0',sets:'',type:'normal',winner:''};worker.matchTimes[id]={a:v.a,b:v.b,startedAt:'2026-10-05T01:00:00Z',endedAt:null};packets.push({type:'school-court-records',version:1,court:'ABCD'[i-1],base:central,state:worker});const merged=E.mergeRecords(integrated,packets.at(-1));assert.equal(merged.conflicts.length,0);integrated=merged.state;}
assert.equal(Object.keys(integrated.entries).length,4,'四場地不可互相覆蓋');const repeated=E.mergeRecords(integrated,packets[0]);assert.equal(repeated.changes.length,0);assert.equal(repeated.duplicates,1);const clash=structuredClone(packets[0]);clash.state.entries.M1.sa='8';assert.equal(E.mergeRecords(integrated,clash).conflicts.length,1);assert.equal(E.mergeRecords(integrated,clash,{M1:'local'}).state.entries.M1.sa,'1');assert.equal(E.mergeRecords(integrated,clash,{M1:'incoming'}).state.entries.M1.sa,'8');const wrong=structuredClone(packets[0]);wrong.state.id='other';assert.throws(()=>E.mergeRecords(integrated,wrong));const movedCourt=structuredClone(integrated);movedCourt.assignments.M1.court='B';assert.equal(E.mergeRecords(movedCourt,clash).conflicts.length,1);const tamper=structuredClone(packets[0]);tamper.state.entries.M2={sa:'99',sb:'0',sets:'',type:'normal',winner:''};assert.equal(E.mergeRecords(central,tamper).state.entries.M2,undefined,'場地檔不得改其他場次');fs.writeFileSync('sync-test-fixture.json',JSON.stringify({central,packets,clash}));
const finished=structuredClone(integrated),fv=E.resolve(finished).M1;finished.results.M1={a:fv.a,b:fv.b,winner:fv.a,sa:21,sb:12,sets:'',type:'normal'};delete finished.entries.M1;finished.matchTimes.M1.endedAt='2026-10-05T01:30:00Z';const finalPacket={type:'school-court-records',version:1,court:'A',base:integrated,state:finished};const finals=E.mergeRecords(integrated,finalPacket);assert.equal(finals.conflicts.length,0);assert.equal(finals.state.results.M1.winner,fv.a);assert.equal(E.resolve(finals.state).M5.a,fv.a);const staleChoice=structuredClone(clash);staleChoice.expected={M1:E.matchRecord(central,'M1')};assert.equal(E.mergeRecords(integrated,staleChoice,{M1:'incoming'}).conflicts.length,1,'確認前又有變更，不可覆蓋');
const paused=structuredClone(central);paused.locked=false;assert.equal(E.mergeRecords(central,{type:'school-court-records',version:1,court:'*',base:central,state:paused}).state.locked,false);
assert.equal(E.best3('1:0, 0:1').complete,false);assert.throws(()=>E.best3('1:0, 0:1',true));assert.equal(E.best3('1:0, 1:0',true).sa,2);assert.equal(E.best3('0:1, 1:0, 0:1',true).sb,2);assert.throws(()=>E.best3('1:0, 1:0, 0:1'));assert.throws(()=>E.best3('1:1'));assert.equal(E.best3Change({sets:'1:0, 0:1'},'b',-1).sets,'1:0');assert.throws(()=>E.best3Change({sets:'1:0, 0:1'},'a',-1));const tug=state(4,'single');tug.settings.score='best3';const tg=E.resolve(tug).M1;tug.results.M1={a:tg.a,b:tg.b,winner:tg.a,sa:2,sb:1,sets:'1:0, 0:1, 1:0',type:'normal'};assert.equal(E.validate(tug).results.M1.sa,2);const ruled=structuredClone(tug);ruled.results.M1={a:tg.a,b:tg.b,winner:tg.b,sa:1,sb:1,sets:'1:0, 0:1',type:'decision'};assert.equal(E.validate(ruled).results.M1.winner,tg.b);const invalidTug=structuredClone(tug);invalidTug.results.M1.sets='1:0';assert.throws(()=>E.validate(invalidTug));
console.log('PASS: best-of-three progress, two-win finish, undo, illegal extra rounds and tied-score referee decisions.');
console.log('PASS: four offline court merges, repeat imports, manual conflicts, reassignment and event isolation.');
console.log(`PASS: ${schedules} schedules: interleaving, rest guidance, court conflicts, reset final, delayed finish and preserved actual times.`);
console.log(`PASS: ${checks} complete tournament simulations; 100 fair draw structure checks; sequential restore, result correction, roster, backup and actual-time validation.`);

// Exercise the actual result handler: a tied or unfinished score must persist without advancing.
const recordSource=html.slice(html.indexOf('function record(row,id)'),html.indexOf('\nfunction ',html.indexOf('function record(row,id)')+1));
for(const example of [{mode:'total',a:'10',b:'10',sets:''},{mode:'total',a:'0',b:'0',sets:''},{mode:'best3',a:'1',b:'1',sets:'1:0, 0:1'},{mode:'best3',a:'1',b:'0',sets:'1:0'}]){
 const sample=state(4,'single');sample.settings.score=example.mode;const match=E.resolve(sample).M1;sample.matchTimes={M1:{a:match.a,b:match.b,startedAt:'2026-10-04T09:00:00Z',endedAt:null}};
 const fields={'.resultType':{value:'normal'},'.sa':{value:example.a},'.sb':{value:example.b},'.sets':{value:example.sets},'.winner':{value:''}};let saved=0,message='';
 const context={Engine:E,state:sample,log:()=>{},save:()=>saved++,render:()=>{},notify:m=>message=m};vm.createContext(context);vm.runInContext(recordSource,context);context.record({querySelector:key=>fields[key]},'M1');
 assert.equal(saved,1);assert.equal(sample.entries.M1.sa,example.a);assert.equal(sample.entries.M1.sb,example.b);assert.equal(sample.results.M1,undefined);assert.equal(sample.matchTimes.M1.endedAt,null);assert.match(message,/已保存/);E.validate(JSON.parse(JSON.stringify(sample)));
 // Editing a completed match to a tie preserves its confirmed result until a winner is confirmed.
 sample.results.M1={a:match.a,b:match.b,sa:2,sb:0,sets:example.mode==='best3'?'1:0, 1:0':'',winner:match.a,type:'normal'};const confirmed=JSON.stringify(sample.results);context.record({querySelector:key=>fields[key]},'M1');assert.equal(JSON.stringify(sample.results),confirmed);assert.match(message,/原有勝負/);
}
console.log('PASS: tied and unfinished scores saved without advancing or clearing confirmed results.');
